version: "3.9"
services:
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./react-frontend/.env

  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-flask
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
